name: Angular CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # Vérifie si un script "lint" existe dans package.json
      - id: check_lint
        name: Check if npm 'lint' script exists
        shell: bash
        run: |
          node -e "try{const p=require('./package.json'); const has=!!(p.scripts && p.scripts.lint); console.log('exists='+has)}catch(e){console.log('exists=false')}" >> "$GITHUB_OUTPUT"

      # Lance le lint uniquement si le script existe
      - name: Run lint
        if: steps.check_lint.outputs.exists == 'true'
        run: npm run lint

      # Sinon, marque explicitement le skip
      - name: Skip lint (no npm 'lint' script)
        if: steps.check_lint.outputs.exists != 'true'
        run: echo "No npm 'lint' script found — skipping."

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Run unit tests
        env:
          CI: true
        run: npm test

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Run TypeScript type check
        run: npx tsc --noEmit

  build:
    needs: [lint, test, typecheck]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Build Angular app
        env:
          NODE_ENV: production
        run: npm run build -- --configuration=production
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/
          if-no-files-found: error
          retention-days: 7

  security:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Run npm audit (critical only)
        run: npm audit --omit=dev --audit-level=critical
      - name: Run npm audit (full report)
        run: npm audit --json > npm-audit.json || true
      - name: Upload npm audit report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit.json
          retention-days: 7
